services:
  php:
    build:
      target: ci
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html/
  node:
    build:
      target: ci
      dockerfile: Dockerfile.node
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
  mailpit:
    image: axllent/mailpit
  schedule:
    build:
      target: ci
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html/
  horizon:
    build:
      target: ci
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html/
